name             'devstack'
maintainer       'Christoph Lukas'
maintainer_email 'lukas@pingworks.de'
license          'All rights reserved'
description      'Installs/Configures devstack'
long_description 'Installs/Configures devstack'
version          '0.1.0'

depends 'apt'
depends 'pw_base'
depends 'pw_dockerhost'
depends 'pw_openvpn'
depends 'pw_dnsmasq'
depends 'pw_wpasupplicant'
